name = "Gulo Industries Pack"
author = "Hubble the Wolverine"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5aae5117c47ee26d50f37892a25129a72d6e5ba88d94aacd42046c44d51b0b03"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
