name = "Gulo Industries Pack"
author = "Koda+Hubble"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "472a6e8ab33bb49bf819df3b93b98477f7ca267503fd95c7fb788e99c33d2b2a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
