#General configuration settings
[general]
	scaledFallDamage = false
	scaledMotion = true
	scaledReach = false
	scaledAttack = false
	scaledDefense = false
	scaledHealth = false
	scaledItemDrops = false
	scaledProjectiles = false
	scaledExplosions = false
	keepAllScalesOnRespawn = true
	accurateNetherPortals = true
	scalesKeptOnRespawn = []
	enableCommands = true
	enableDebugCommands = false
