#Whether to where if Player/Mob Drops will be put into the Gravestone
GravestoneOnDeath = true
#Percentage of amount that items are lost
# Default: 100.0
# Range: 0.0 ~ 100.0
ItemLostPercentage = 100.0
#Distance to merge graves instead of placing a new grave
# Default: 5
# Range: 1 ~ 256
GraveMaxDistance = 5
#Time till the grave despawns in Ticks
# Default: 72000
# Range: 1 ~ 864000
MaxGraveLifespan = 864000
#Whether to allow grave merging
GraveMerging = true
#Whether to allow grave to spawn with no drops
EmptyGraves = false
#Whether to allow coarse to spawn under graves
CoarseDirtBelowGraves = false
#Whether to text to be displayed above the gravestone for a non player entity
NonPlayerGraveTitles = false
#A whitelist of entities to be able to drop graves.
EntitiesGraves = ["minecraft:player"]
